packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@t3-oss/env-core": ^0.13.8
  "@tailwindcss/postcss": ^4.1.13
  "@tailwindcss/typography": ^0.5.19
  "@tanstack/react-devtools": ^0.7.1
  "@tanstack/react-query": ^5.90.2
  "@tanstack/react-query-devtools": ^5.90.2
  "@tanstack/react-router": ^1.132.29
  "@tanstack/react-router-devtools": ^1.132.29
  "@tanstack/react-router-ssr-query": ^1.132.29
  "@tanstack/react-start": ^1.132.29
  "@tanstack/router-plugin": ^1.132.29
  "@trpc/client": ^11.4.0
  "@trpc/server": ^11.4.0
  "@trpc/tanstack-react-query": ^11.4.0
  "@types/node": ^22.15.29
  date-fns: 4.1.0
  dotenv-cli: ^8.0.0
  jsdom: ^27.0.0
  postcss: ^8.5.6
  superjson: ^2.2.2
  tailwindcss: 4.1.13
  tsup: ^8.5.0
  typescript: ^5.9.3
  web-vitals: ^5.1.0
  zod: 4.1.11
  zustand: ^5.0.8
catalogs:
  betterAuth:
    better-auth: ^1.3.24
    "@better-auth/expo": ^1.3.24
    "@better-auth/cli": ^1.3.24
  react19:
    "@types/react": ^19.1.9
    "@types/react-dom": ^19.1.7
    react: 19.1.0
    react-dom: 19.1.0
  viteConfig:
    "@tailwindcss/vite": ^4.1.13
    "@vitejs/plugin-react": ^5.0.4
    vite: ^7.1.7
    vite-tsconfig-paths: ^5.1.4
    vitest: ^3.2.4

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
