version: "3.8"

services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voltig
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  db_data:
